name: CI for Project

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

  workflow_dispatch:

jobs:
  Main_CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Node Setup
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
      - name: Install dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint

      - name: Run Unit Tests Vitest
        run: npm run test:unit

      - name: Run Build
        run: npm run build
